/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.control.DAOCliente;
import br.com.control.DAOEndereco;
import br.com.model.Cliente;
import br.com.model.Endereco;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Renan
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        //initMaximizado();
        Show_Products_In_JTable();
    }
    
    private void initMaximizado(){
        int inset = 5;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(inset, inset, screenSize.width - inset *2, screenSize.height - inset *2);
        this.setVisible(true);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cdCnpj = new javax.swing.JTextField();
        nmNomeFantasia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jButtonIncluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nuTelefone = new javax.swing.JTextField();
        jButtonAlterar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nmRua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nmComplemento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nmBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nmCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nmEstado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nmPais = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nmCep = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nmNumero = new javax.swing.JTextField();
        jButtonLimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cdIdCliente = new javax.swing.JLabel();
        cdIdEndereco = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        Venda = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Cnpj:");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome Fantasia:");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setOpaque(true);

        nmNomeFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmNomeFantasiaActionPerformed(evt);
            }
        });

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Cliente", "Cnpj", "Nome Fantasia", "Rua", "Complemento", "Número", "Cep", "Bairro", "Cidade", "Estado", "Pais", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente.setColumnSelectionAllowed(true);
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);
        jTableCliente.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Telefone:");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setOpaque(true);

        nuTelefone.setText("()");
        nuTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuTelefoneActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonDeletar.setText("Deletar");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Rua:");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setOpaque(true);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Complemento:");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setOpaque(true);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Bairro:");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setOpaque(true);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Cidade:");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel11.setOpaque(true);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Estado:");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setOpaque(true);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Pais:");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.setOpaque(true);

        nmPais.setEditable(false);
        nmPais.setText("Brasil");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("CEP:");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.setOpaque(true);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Número:");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setOpaque(true);

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        cdIdEndereco.setText(".");

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addGap(79, 79, 79)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addGap(87, 87, 87)
                        .addComponent(jButtonDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addGap(85, 85, 85)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addGap(73, 73, 73)
                        .addComponent(jButtonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)
                        .addComponent(nmComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nmBairro)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nmNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(nmCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nmEstado)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nmPais, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel3)
                                .addGap(43, 43, 43)
                                .addComponent(cdIdCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cdIdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonLimpar)))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nuTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cdCnpj)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nmNomeFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                                    .addComponent(nmCep)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nmRua)))
                        .addGap(10, 10, 10))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel2, jLabel6, jLabel7, jLabel9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cdCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nmNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nuTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(nmCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nmRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nmComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(nmBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nmCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(nmEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nmPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(nmNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jButtonLimpar)
                        .addComponent(cdIdEndereco))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cdIdCliente)))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonDeletar)
                    .addComponent(jButtonConsultar)
                    .addComponent(jButtonVoltar))
                .addGap(16, 16, 16))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel2, jLabel6, jLabel7, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAlterar, jButtonConsultar, jButtonDeletar, jButtonIncluir});

        jMenu2.setText("File");

        jMenuItem2.setText("Cadastrar Cliente");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Cadastrar Produto");
        jMenu2.add(jMenuItem3);

        jMenuItem7.setText("Sair");
        jMenu2.add(jMenuItem7);

        Venda.add(jMenu2);

        jMenu5.setText("Venda");

        jMenuItem8.setText("Solicitação de venda");
        jMenu5.add(jMenuItem8);

        jMenuItem11.setText("Vendas efetuadas");
        jMenu5.add(jMenuItem11);

        jMenuItem9.setText("Estornar venda");
        jMenu5.add(jMenuItem9);

        Venda.add(jMenu5);

        jMenu3.setText("Relatório");

        jMenuItem4.setText("Relatório de vendas por Cliente");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Relatário de vendas por Produto");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Relatório de vendas por Período");
        jMenu3.add(jMenuItem6);

        Venda.add(jMenu3);

        jMenu7.setText("Estoque");

        jMenuItem10.setText("Cadastro de estoque");
        jMenu7.add(jMenuItem10);

        Venda.add(jMenu7);

        setJMenuBar(Venda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nmNomeFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmNomeFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmNomeFantasiaActionPerformed
    //Botão Incluir
    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        Cliente cliente = new Cliente();
        Endereco endereco = new Endereco();

        int idCliente = DAOCliente.gerarSequencialIdCliente();
        //int idEndereco = DAOEndereco.gerarSequencialIdEndereco();
             
        cliente.setCdCnpj(cdCnpj.getText());
        cliente.setNmNomeFantasia(nmNomeFantasia.getText());
        cliente.setNuTelefone(nuTelefone.getText());

        cliente.setIdCliente(idCliente);
       // cliente.setIdEndereco(idEndereco);
        
        //endereco.setIdEndereco(idEndereco);
        endereco.setNmRua(nmRua.getText());
        endereco.setNmComplemento(nmComplemento.getText());
        endereco.setNmBairro(nmBairro.getText());
        endereco.setNmCidade(nmCidade.getText());
        endereco.setNmEstado(nmEstado.getText());
        endereco.setNmPais(nmPais.getText());
        endereco.setNmNumero(nmNumero.getText());
        endereco.setNmCep(nmCep.getText());
        
        //DAOEndereco daoEndereco = new DAOEndereco();
        //daoEndereco.inserirEndereco(endereco);
        
        DAOCliente daoCliente = new DAOCliente();
        daoCliente.inserirCliente(cliente);
        Show_Products_In_JTable();
        
        JOptionPane.showMessageDialog(null, "Sucesso!");
      
        this.dispose();
        TelaCliente telaCliente = new TelaCliente();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        Cliente cliente = new Cliente();
        Endereco endereco = new Endereco();

        //int idCliente = DAOCliente.gerarSequencialIdCliente();
        //int idEndereco = DAOEndereco.gerarSequencialIdEndereco();
             
        cliente.setCdCnpj(cdCnpj.getText());
        cliente.setNmNomeFantasia(nmNomeFantasia.getText());
        cliente.setNuTelefone(nuTelefone.getText());

        cliente.setIdCliente(Integer.parseInt(cdIdCliente.getText()));
        cliente.setIdEndereco(Integer.parseInt(cdIdEndereco.getText()));
        
        endereco.setIdEndereco(Integer.parseInt(cdIdEndereco.getText()));
        endereco.setNmRua(nmRua.getText());
        endereco.setNmComplemento(nmComplemento.getText());
        endereco.setNmBairro(nmBairro.getText());
        endereco.setNmCidade(nmCidade.getText());
        endereco.setNmEstado(nmEstado.getText());
        endereco.setNmPais(nmPais.getText());
        endereco.setNmNumero(nmNumero.getText());
        endereco.setNmCep(nmCep.getText());
        
        DAOEndereco daoEndereco = new DAOEndereco();
        daoEndereco.alterarEndereco(endereco);
        
        DAOCliente daoCliente = new DAOCliente();
        daoCliente.alterarCliente(cliente);
        Show_Products_In_JTable();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void nuTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuTelefoneActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        int index = jTableCliente.getSelectedRow();
        ShowItem(index);
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        cdIdCliente.setText("");
        cdCnpj.setText("");
        nmNomeFantasia.setText("");
        nuTelefone.setText("");
        
        cdIdEndereco.setText("");
        nmCep.setText("");
        nmRua.setText("");
        nmBairro.setText("");
        nmComplemento.setText("");
        nmCidade.setText("");
        //nmPais.setText("");
        nmNumero.setText("");
        nmEstado.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        Cliente cliente = new Cliente();
        Endereco endereco = new Endereco();

        cliente.setIdCliente(Integer.parseInt(cdIdCliente.getText()));
        cliente.setIdEndereco(Integer.parseInt(cdIdEndereco.getText()));
        
        endereco.setIdEndereco(Integer.parseInt(cdIdEndereco.getText()));
              
        DAOCliente daoCliente = new DAOCliente();
        daoCliente.deletarCliente(cliente);
        
        DAOEndereco daoEndereco = new DAOEndereco();
        daoEndereco.deletarEndereco(endereco);
        Show_Products_In_JTable();
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        if(cdCnpj.getText().equals("")){
            Show_Products_In_JTable();
        }else{
            Cliente pCliente = new Cliente();
            pCliente.setCdCnpj(cdCnpj.getText());
            Cliente clienteConsulta = DAOCliente.consultarPorChavePrimariaCliente(pCliente);
        
            if(clienteConsulta ==  null){
                JOptionPane.showMessageDialog(null, "CNPJ não existe na base de dados");
            }else{
                DefaultTableModel model = (DefaultTableModel)jTableCliente.getModel();
                // clear jtable content
                model.setRowCount(0);
                Object[] row = new Object[14];

                Endereco endereco = getEnderecoPorCliente(clienteConsulta.getIdEndereco());
                row[0] = clienteConsulta.getIdCliente();
                row[1] = clienteConsulta.getCdCnpj();
                row[2] = clienteConsulta.getNmNomeFantasia();
                row[3] = endereco.getNmRua();
                row[4] = endereco.getNmComplemento();
                row[5] = endereco.getNmNumero();
                row[6] = endereco.getNmCep();
                row[7] = endereco.getNmBairro();
                row[8] = endereco.getNmCidade() ;
                row[9] = endereco.getNmEstado();
                row[10] = endereco.getNmPais();
                row[11] = endereco.getNmCep();
                row[12] = endereco.getNmTelefone();

                model.addRow(row);
            }
        }
        
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void checkCampo(){
        if(cdCnpj.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Favor preencher o CNPJ!");
        }
        if(nmNomeFantasia.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Favor preencher o NOME FANTASIA!");
        }  
        /*if(nmRua.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Favor preencher o RUA!");
        }
        if(nmComplemento.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Favor preencher o COMPLEMENTO!");
        }
        if(nmBairro.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Favor preencher o BAIRRO!");
        }*/
        if(nuTelefone.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Favor preencher o CIDADE!");
        }
        /*if(nmEstado.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Favor preencher o ESTADO!");
        }*/
    }
    
    public void Show_Products_In_JTable()
    {
        ArrayList<Cliente> list = DAOCliente.consultarCliente();
        
        DefaultTableModel model = (DefaultTableModel)jTableCliente.getModel();
        // clear jtable content
        model.setRowCount(0);
        Object[] row = new Object[14];
        for(int i = 0; i < list.size(); i++)
        {
            Cliente clienteLista = list.get(i);
            
            Endereco endereco = getEnderecoPorCliente(clienteLista.getIdEndereco());
            row[0] = list.get(i).getIdCliente();
            row[1] = list.get(i).getCdCnpj();
            row[2] = list.get(i).getNmNomeFantasia();
            row[3] = endereco.getNmRua();
            row[4] = endereco.getNmComplemento();
            row[5] = endereco.getNmNumero();
            row[6] = endereco.getNmCep();
            row[7] = endereco.getNmBairro();
            row[8] = endereco.getNmCidade() ;
            row[9] = endereco.getNmEstado();
            row[10] = endereco.getNmPais();
            row[11] = endereco.getNmCep();
            row[12] = endereco.getNmTelefone();
            
            
            model.addRow(row);
        }
    
    }
    
    private Endereco getEnderecoPorCliente(Integer idEndereco){
        Endereco endereco = new Endereco();
        if(idEndereco != null){
            endereco.setIdEndereco(idEndereco);
            endereco = DAOEndereco.consultarPorChavePrimariaEndereco(endereco);
        }
        
        
        return endereco;
    }
    
    // Show Data In Inputse
    public void ShowItem(int index)
    {
        ArrayList<Cliente> listCliente = DAOCliente.consultarCliente();
        Cliente cliente = listCliente.get(index);
        Endereco endereco = getEnderecoPorCliente(cliente.getIdEndereco());
        
        cdIdCliente.setText(Integer.toString(cliente.getIdCliente()));
        cdCnpj.setText(cliente.getCdCnpj());
        nmNomeFantasia.setText(cliente.getNmNomeFantasia());
        nuTelefone.setText(cliente.getNuTelefone());
        
        cdIdEndereco.setText(Integer.toString(endereco.getIdEndereco()));
        nmCep.setText(endereco.getNmCep());
        nmRua.setText(endereco.getNmRua());
        nmBairro.setText(endereco.getNmBairro());
        nmComplemento.setText(endereco.getNmComplemento());
        nmCidade.setText(endereco.getNmCidade());
        nmPais.setText(endereco.getNmPais());
        nmNumero.setText(endereco.getNmNumero());
        nmEstado.setText(endereco.getNmEstado());
        
        
    }
    
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Venda;
    private javax.swing.JTextField cdCnpj;
    private javax.swing.JLabel cdIdCliente;
    private javax.swing.JLabel cdIdEndereco;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField nmBairro;
    private javax.swing.JTextField nmCep;
    private javax.swing.JTextField nmCidade;
    private javax.swing.JTextField nmComplemento;
    private javax.swing.JTextField nmEstado;
    private javax.swing.JTextField nmNomeFantasia;
    private javax.swing.JTextField nmNumero;
    private javax.swing.JTextField nmPais;
    private javax.swing.JTextField nmRua;
    private javax.swing.JTextField nuTelefone;
    // End of variables declaration//GEN-END:variables
}
